### ISSUE TITLE
broken preview for community-docs and other components

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit-dev#287]
Getting this error in the component preview:

```
compositions.c957bd669dac07301f94.js:1 Uncaught TypeError: e.O is not a function
    at compositions.c957bd669dac07301f94.js:1:212
    at t (/api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-preview.js:1:1359874)
    at Array.forEach (<anonymous>)
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-preview.js:1:1359994
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-preview.js:1:1360054
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-preview.js:1:1360178
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-preview.js:1:263
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-preview.js:1:267
compositions.c957bd669dac07301f94.js:1 Uncaught TypeError: e.O is not a function
    at compositions.c957bd669dac07301f94.js:1:212
    at t (/api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-component.js:1:1315268)
    at Array.forEach (<anonymous>)
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-component.js:1:1315388
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-component.js:1:1315448
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-component.js:1:1354244
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-component.js:1:247
    at /api/teambit.docs/ui/community-docs@1.95.17/~aspect/component-preview/teambit_docs_ui_community_docs-component.js:1:251
696.js:12 Uncaught (in promise) Error: Preview for name: compositions was not found
    at HTMLScriptElement.i.onload (696.js:12:4642)
```

direct url:
https://e14fbt7o.scopes.teambit.cloud/api/teambit.community/envs/community-react@1.95.6/~aspect/env-template/compositions/#teambit.docs/ui/community-docs@1.95.17?preview=compositions&BasicCommunityDocs

> working preview (for comparison):
> https://hu9y25l.scopes.teambit.cloud/api/teambit.react/react/~aspect/env-template/compositions/#teambit.base-ui/input/button@1.0.4?preview=compositions&BasicButton

**Comment by KutnerUri** [comment]
bit insight shows these cyclic dependencies:

```
❯ bit insights
Found 6 cycles.

Cyclic dependency
-----------------
- teambit.base-react/navigation/link@2.0.16
- learnbit.base-react/navigation/my-router@0.0.3
- learnbit.base-react/navigation/my-router-adapter@0.0.3

Cyclic dependency
-----------------
- teambit.ui-foundation/ui/navigation/react-router-adapter@6.0.5
- teambit.design/ui/layouts/sections/left-right@1.90.6
- teambit.base-react/navigation/link@2.0.18
- teambit.community/envs/community-react@1.90.7

Cyclic dependency
-----------------
- teambit.ui-foundation/ui/navigation/react-router-adapter@1.95.0
- teambit.design/ui/layouts/sections/left-right@1.95.0
- teambit.base-react/navigation/link@1.95.0
- teambit.community/envs/community-react@1.95.0

Cyclic dependency
-----------------
- teambit.community/ui/use-cases/use-cases-card-grid@1.95.0
- teambit.community/entity/use-cases@1.95.0

Cyclic dependency
-----------------
- teambit.ui-foundation/ui/navigation/react-router-adapter@6.0.10
- teambit.community/envs/community-react@1.95.4
- teambit.design/ui/layouts/sections/left-right@1.95.4
- teambit.base-react/navigation/link@2.0.23

Cyclic dependency
-----------------
- teambit.community/ui/use-cases/use-cases-section@1.95.1
- teambit.community/ui/logo-showcase@1.95.1
- teambit.community/ui/use-cases/use-cases-card-grid@1.95.1
- teambit.community/entity/use-cases@1.95.2
- teambit.community/entity/images@1.95.3
- teambit.community/ui/pages/homepage@1.95.1
- teambit.community/ui/usage-example@0.0.3
- teambit.community/ui/text-tooltip@0.0.4

Found 61 duplicate dependencies.
```
