### ISSUE TITLE
error "Maximum call stack size exceeded" during build in GH PRs

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit-dev#330]
getting this error during the build step of the github "tests" action:
```
Maximum call stack size exceeded
```
as seen here - https://github.com/teambit/bit-dev/runs/5648548548?check_suite_focus=true

It is happening _consistently_ during the `teambit.preview/preview:GenerateEnvTemplate` step of the build, after loading the 3 envs of the project.

**Comment by KutnerUri** [comment]
Managed to reproduce it locally, like so:

<details><summary>terminal output</summary>

```
❯ cd /tmp          
❯ git clone https://github.com/teambit/bit-dev.git                                     
Cloning into 'bit-dev'...                                                                                                                                                                                                                   
❯ cd bit-dev 
❯ export NODE_OPTIONS=--max_old_space_size=4096                          
❯ bit install                                              
✖ couldn't load one of the following extensions teambit.community/apps/bit-dev@1.95.30, please use the '--log=error' flag for the full error.
  Resolving component dependencies for workspace: 'bit.dev'
✔ all objects were processed and written to the filesystem successfully
  installing dependencies in workspace using teambit.dependencies/pnpm
✖ error: unable to load the extension "teambit.community/envs/community-react@1.95.7", please use the '--log=error' flag for the full error.
⚠ environment with ID: teambit.community/envs/community-react@1.95.7 was not found
⚠ environment with ID: "teambit.community/envs/community-react" is not configured as extension.
you probably need to add this environment as a key to your variant in the workspace.jsonc. for example, "your-variant": { "teambit.community/envs/community-react": {} }

⚠ environment with ID: "teambit.community/envs/community-react@1.95.1" is not configured as extension.
you probably need to add this environment as a key to your variant in the workspace.jsonc. for example, "your-variant": { "teambit.community/envs/community-react@1.95.1": {} }

✖ error: unable to load the extension "teambit.community/envs/community-mdx@1.95.9", please use the '--log=error' flag for the full error.
⚠ environment with ID: teambit.community/envs/community-mdx@1.95.9 was not found
⚠ environment with ID: "teambit.community/envs/community-mdx@1.95.8" is not configured as extension.
you probably need to add this environment as a key to your variant in the workspace.jsonc. for example, "your-variant": { "teambit.community/envs/community-mdx@1.95.8": {} }

⚠ environment with ID: "teambit.community/envs/community-mdx" is not configured as extension.
you probably need to add this environment as a key to your variant in the workspace.jsonc. for example, "your-variant": { "teambit.community/envs/community-mdx": {} }

✔ running pre install subscribers
✔ deduping dependencies for installation
Already up-to-date
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/kutner/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1450, reused 1450, downloaded 0, added 1456, done
node_modules/.pnpm/registry.npmjs.org+core-js-pure@3.21.1/node_modules/core-js-pure: Running postinstall script, done in 137ms
node_modules/.pnpm/registry.npmjs.org+core-js@3.21.1/node_modules/core-js: Running postinstall script, done in 171ms
node_modules/.pnpm/registry.npmjs.org+esbuild@0.11.10/node_modules/esbuild: Running postinstall script, done in 884ms
node_modules/.pnpm/registry.npmjs.org+sharp@0.29.3/node_modules/sharp: Running install script, done in 1.7s

dependencies:
[...]

❯ bit compile 
✖ couldn't load one of the following extensions teambit.community/apps/bit-dev@1.95.30, please use the '--log=error' flag for the full error.

[...]

✔ 287/287 components compiled successfully.
Finished. (37s)

❯ bit check-types                                                   
completed type checking (14.752 sec). no errors were found.
                                                                                                                                                                                                                   
bit-dev git:master*  48s
❯ bit build --all
✔ found 287 components to build
✔ running pre install subscribers
✔ deduping dependencies for installation
...313ce24089972a0cc0cc129c2324e04fb1104 |  WARN  deprecated subscriptions-transport-ws@0.11.0
...313ce24089972a0cc0cc129c2324e04fb1104 |    +1009 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/kutner/.pnpm-store/v3
  Virtual store is at:             ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/node_modules/.pnpm
...313ce24089972a0cc0cc129c2324e04fb1104 | Progress: resolved 1009, reused 1005, downloaded 4, added 1009, done
../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/node_modules/.pnpm/registry.npmjs.org+core-js@3.21.1/node_modules/core-js: Running postinstall script, done in 134ms
../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/node_modules/.pnpm/registry.npmjs.org+esbuild@0.11.10/node_modules/esbuild: Running postinstall script, done in 874ms
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
  running build pipe for 5 environments, total 36 tasks
  generated graph for env "teambit.react/react", originalSeedersOfThisEnv: 5, graphOfThisEnv: 5, graph total: 28
  generated graph for env "teambit.community/envs/community-mdx@1.95.9", originalSeedersOfThisEnv: 167, graphOfThisEnv: 167, graph total: 206
  generated graph for env "teambit.harmony/node", originalSeedersOfThisEnv: 15, graphOfThisEnv: 15, graph total: 38
  generated graph for env "teambit.harmony/aspect", originalSeedersOfThisEnv: 3, graphOfThisEnv: 3, graph total: 232
  generated graph for env "teambit.community/envs/community-react@1.95.7", originalSeedersOfThisEnv: 97, graphOfThisEnv: 97, graph total: 258
✔ executing pre-build for all tasks
✔ env "teambit.harmony/aspect", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 386μs
✔ env "teambit.community/envs/community-react@1.95.7", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 2ms
✔ env "teambit.harmony/node", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 79μs
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 47μs
✔ env "teambit.community/envs/community-mdx@1.95.9", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 1ms
✔ env "teambit.harmony/aspect", task "teambit.compilation/compiler:BabelCompiler (compile components for artifact dist)" has completed successfully in 1s
✔ env "teambit.harmony/aspect", task "teambit.compilation/compiler:TypescriptCompiler (compile components for artifact declaration)" has completed successfully in 2m
✔ env "teambit.community/envs/community-react@1.95.7", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 14s
✔ env "teambit.harmony/node", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 865ms
✔ env "teambit.react/react", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 5s
✔ env "teambit.community/envs/community-mdx@1.95.9", task "teambit.compilation/compiler:MDXCompiler (compile components)" has completed successfully in 12s
✔ env "teambit.harmony/aspect", task "teambit.defender/tester:TestComponents" has completed successfully in 28ms
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_blocks_sidebar@1.95.12/dist/node-title/node-title.spec.js (6.489 s)
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_cards_next-page@1.95.12/dist/next-page.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.base-react_ui_layout_graph-node@1.95.7/dist/graph-node.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_community-highlighter@1.95.14/dist/community-highlighter.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_navigation_tab-link@1.95.7/dist/tab-link.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_graph_grid-graph@1.95.16/dist/grid-graph.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_plugins_explore-section@1.95.13/dist/explore-section.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_plugins_create-section@1.95.13/dist/create-section.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_styles_scrollbar@1.95.7/dist/scrollbar.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_blocks_footer@1.95.7/dist/category/category.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.bit_quick-start_learn-crossroad@0.0.14/dist/learn-crossroad.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_navigation_icon-link@1.95.7/dist/icon-link.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_use-cases_use-cases-card@1.95.9/dist/use-cases-card.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.bit_quick-start_card@0.0.21/dist/card.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_ui_hooks_use-element-on-fold@1.95.7/dist/use-element-on-fold.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_blocks_sidebar@1.95.12/dist/docs-tree-node/docs-tree-node.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_blocks_footer@1.95.7/dist/footer.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_footer_category@1.95.8/dist/category.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.bit_quick-start_featured@0.0.23/dist/featured.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.base-react_buttons_button@1.95.7/dist/button.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_bubble-highlighter@1.95.11/dist/bubble-highlighter.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_hooks_use-local-storage@1.95.9/dist/use-local-storage.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_ui_pages_doc-page@1.95.13/dist/doc-page.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_ui_navigation_table-of-content@1.95.7/dist/table-of-content.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_terminal@1.95.8/dist/terminal.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_cloud_create-account@0.0.16/dist/create-account.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_graph_component-bubble@1.95.14/dist/component-bubble.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.base-react_content_image@1.95.7/dist/image.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_github-stars@1.95.8/dist/github-stars.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_use-cases_use-cases-section@1.95.13/dist/use-cases-section.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_sections_left-right@1.95.12/dist/left-right.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_sections_top-down@1.95.12/dist/top-down.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_use-cases_use-cases-card-grid@1.95.11/dist/use-cases-card-grid.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_navigation_menu@1.95.7/dist/menu.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_features_features-card@1.95.8/dist/features-card.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_content_subtitle@1.95.8/dist/subtitle.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_ui_highlighter_highlight-component@1.95.11/dist/highlight-component.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_content_heading@1.95.12/dist/heading.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_heading@1.95.13/dist/heading.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.docs_ui_subtitle@1.95.7/dist/subtitle.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_sticky-menu@1.95.8/dist/sticky-menu.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_pages_errors_not-found@1.95.8/dist/not-found.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_cards_bubble-card@1.95.8/dist/bubble-card.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_pages_plugins@1.95.13/dist/plugins.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_cards_card@1.95.8/dist/card.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_content_caption@1.95.7/dist/caption.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.base-react_layout_grid@1.95.7/dist/grid.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.base-react_content_video@1.95.7/dist/video.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_pages_page@1.95.8/dist/page.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_navigation_link@1.95.7/dist/link.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.base-react_pages_page@1.95.7/dist/page.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.design_ui_brand_logo@1.95.7/dist/logo.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_hooks_use-stars@1.95.7/dist/use-stars.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_ui_browser@1.95.8/dist/browser.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_component-showcase@0.0.29/dist/component-showcase.spec.js

Test Suites: 35 skipped, 55 passed, 55 of 90 total
Tests:       39 skipped, 133 passed, 172 total
Snapshots:   0 total
Time:        60.849 s
Ran all test suites.
✔ env "teambit.community/envs/community-react@1.95.7", task "teambit.defender/tester:TestComponents" has completed successfully in 1m
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.community_entity_use-cases@1.95.11/dist/use-cases.spec.js

Test Suites: 1 skipped, 1 passed, 1 of 2 total
Tests:       1 skipped, 1 passed, 2 total
Snapshots:   0 total
Time:        3.277 s
Ran all test suites.
✔ env "teambit.harmony/node", task "teambit.defender/tester:TestComponents" has completed successfully in 11s
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.explorer_ui_gallery_component-card-group@1.95.3/dist/component-card-group.spec.js
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.explorer_ui_search_search-input@1.95.3/dist/search-input.spec.js
  ● Console

    console.error
      Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
          at input
          at Text (/Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/node_modules/.pnpm/registry.npmjs.org+@teambit+design.ui.input.text@0.1.5_react-dom@17.0.2+react@17.0.2/node_modules/@teambit/design.ui.input.text/text.tsx:31:24)
          at div
          at IconText (/Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/node_modules/.pnpm/registry.npmjs.org+@teambit+design.ui.input.icon-text@0.0.7_react-dom@17.0.2+react@17.0.2/node_modules/@teambit/design.ui.input.icon-text/icon-text.tsx:27:3)
          at SearchInput (/Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.explorer_ui_search_search-input@1.95.3/search-input.tsx:6:31)
          at SearchInputWithValue

      at printWarning (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at checkControlledValueProps (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:1323:7)
      at initWrapperState (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:1495:5)
      at setInitialProperties (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:9099:7)
      at finalizeInitialChildren (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:10201:3)
      at completeWork (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:19470:17)
      at completeUnitOfWork (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22812:16)
      at performUnitOfWork (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22787:5)
      at workLoopSync (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/.pnpm/registry.npmjs.org+react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:25482:3)


Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        0.859 s
Ran all test suites.
✔ env "teambit.react/react", task "teambit.defender/tester:TestComponents" has completed successfully in 2s
 PASS  ../../../Users/kutner/Library/Caches/Bit/capsules/7ed313ce24089972a0cc0cc129c2324e04fb1104/teambit.bit_quick-start@0.0.24/dist/quick-start.spec.js
  ✓ should render with the correct text (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.42 s
Ran all test suites.
✔ env "teambit.community/envs/community-mdx@1.95.9", task "teambit.defender/tester:TestComponents" has completed successfully in 2s
✔ env "teambit.harmony/aspect", task "teambit.harmony/application:build_application" has completed successfully in 1m
✔ env "teambit.harmony/aspect", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 21ms
Maximum call stack size exceeded
```

</details>

**Comment by KutnerUri** [comment]
high memory usage might be happening because we include a lot of images inside the code. (about 43MB of images, times ~280 components... 11GB? not likely)
Trying it out in this branch - #335

**Comment by KutnerUri** [comment]
fixed by the glorious @GiladShoham
